aspnet/HttpSysServer

src/Microsoft.Net.Http.Server/RequestProcessing/Response.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseHeaderTests.cs

#259 @halter73 @davidfowl 
Note this is going into the 1.0 branch. I'll merge to dev afterwards.
@pranavkm do we run the ServerTests repo tests in the rel branch?

Auto-chunk even for Connection: close responses

---

samples/HelloWorld/Properties/launchSettings.json
samples/HotAddSample/Properties/launchSettings.json
samples/HotAddSample/Startup.cs
samples/SelfHostServer/Properties/launchSettings.json

A user noticed the HotAdd sample was out of date / crashing. Also many of the launch settings are out of date.
@JunTaoLuo @troydai

Update the samples and launchsettings

---

.travis.yml
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/HttpsTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/Properties/AssemblyInfo.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/RequestHeaderTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/RequestTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ServerTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/WebSocketTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/AuthenticationTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/HttpsTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/Properties/AssemblyInfo.cs
test/Microsoft.Net.Http.Server.FunctionalTests/RequestBodyTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/RequestHeaderTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/RequestTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseCachingTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseHeaderTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseSendFileTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ServerTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/WebSocketTests.cs

@Eilon @pranavkm 
Won't pass on travis until https://github.com/aspnet/Testing/pull/236 clears coherence

Enable travis, add conditional OS skips globally

---

README.md

Add AppVeyor status to the readme

---

samples/HelloWorld/project.json
samples/HotAddSample/project.json
samples/SelfHostServer/project.json
src/Microsoft.AspNetCore.Server.WebListener/project.json
src/Microsoft.Net.Http.Server/project.json
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.Tests/project.json

Bump version to 1.0.0.

---

global.json
samples/HelloWorld/project.json
samples/HotAddSample/project.json
samples/SelfHostServer/project.json
src/Microsoft.AspNetCore.Server.WebListener/MessagePump.cs
src/Microsoft.AspNetCore.Server.WebListener/project.json
src/Microsoft.Net.Http.Server/project.json
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ServerTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.Tests/project.json

#302
Also updating the package versions

Backport request draining timeout

---

src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/HeaderCollection.cs

Reacting to HeaderUtilities renames

---

samples/SelfHostServer/Properties/launchSettings.json
samples/SelfHostServer/Startup.cs
src/Microsoft.AspNetCore.Server.HttpSys/Constants.cs
src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/LogHelper.cs
src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/DummyApplication.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/MessagePumpTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Direct address configuration #297

---

README.md

cc @JunTaoLuo 
I deleted and re-recreated the project on AppVeyor. Let's see if it picks up this PR.

Update AppVeyor link/badge

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Disable flaky tests

---

samples/TestClient/App.config
samples/TestClient/TestClient.csproj
src/Microsoft.AspNetCore.Server.HttpSys/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/NativeRequestContext.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/Request.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestContext.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs

#287 - Don't show display names. @leastprivilege
#306 - Use WindowsPrincipal so IsInRole works. @PinpointTownes 
#317 - Close handles. @vanjar

Windows Auth cleanup

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs

Flaky test http://aspnetci/viewLog.html?buildId=192049&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest
See https://github.com/aspnet/HttpSysServer/issues/263#issuecomment-288907777
cc @pranavkm

Disable test

---

src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/MessagePumpTests.cs

React to addition of PreferHostingUrls

---

src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/MessagePumpTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Utilities.cs

This is a clean separation between Stop (graceful) and Dispose (not graceful).

Implement IServer.Stop

---

src/Microsoft.Net.Http.Server/RequestProcessing/NativeRequestContext.cs
src/Microsoft.Net.Http.Server/RequestProcessing/Request.cs

Clean up Windows Auth

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseCachingTests.cs

#263 Adding some details so we can see if this test consistently fails in the same place or if it's just flaky.

Add Caching_SetTtlAndStatusCode_Cached test diagnostics

---

build/dependencies.props
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.csproj

https://github.com/aspnet/Coherence/issues/175

Remove unnecessary package references

---

build/common.props
build/dependencies.props
samples/HotAddSample/HotAddSample.csproj
samples/SelfHostServer/SelfHostServer.csproj
src/Microsoft.AspNetCore.Server.HttpSys/Microsoft.AspNetCore.Server.HttpSys.csproj
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.csproj
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.Tests/Microsoft.AspNetCore.Server.HttpSys.Tests.csproj

Surprisingly didn't have to revert any of the product code changes.
Compare to https://github.com/aspnet/HttpSysServer/commit/31001de66a20d9e056247b558f421afedcf1d0b9

Retarget to netstandard2.0

---

src/Microsoft.AspNetCore.Server.HttpSys/AuthenticationHandler.cs
src/Microsoft.AspNetCore.Server.HttpSys/Microsoft.AspNetCore.Server.HttpSys.csproj
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs

React to forbid changes

---

src/Microsoft.AspNetCore.Server.HttpSys/HttpSysListener.cs
src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/HttpApi.cs
src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/UrlGroup.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Expose a connection limit option

---

src/Microsoft.AspNetCore.Server.HttpSys/FeatureContext.cs
src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/Request.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestStream.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestStreamAsyncResult.cs
src/Microsoft.AspNetCore.Server.HttpSys/StandardFeatureCollection.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/OpaqueUpgradeTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestBodyLimitTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Utilities.cs

#539 Same settings and APIs as kestrel.

Implement request body size limit

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/OpaqueUpgradeTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Addresses https://github.com/aspnet/HttpSysServer/issues/275.

Do not block on async calls

---

test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ServerTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseBodyTests.cs

Skipping tests using dev as a reference. #384

Skip flaky tests

---

build/dependencies.props
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseSendFileTests.cs

The upgrade includes a more self-aware xunit. Changes made to remove all issues found by xunit.analyzers.

Upgrade to xunit 2.3.0-beta4

---

src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Make StopAsync multi-thread safe (#377)

---

src/Microsoft.AspNetCore.Server.HttpSys/StandardFeatureCollection.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/OSDontSkipConditionAttribute.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/OpaqueUpgradeTests.cs

Exclude the upgrade feature if the OS does not support it 

---

src/Microsoft.AspNetCore.Server.HttpSys/Helpers.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestStream.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/ResponseBody.cs

Noticed when doing https://github.com/aspnet/StaticFiles/pull/235

Replace Helpers.CompletedTask and Helpers.CanceledTask

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs

#474 FYI - Merging to quite mass failures.

Skip Auth test due to HttpClient regression 
