aspnet/HttpSysServer

test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.Tests/project.json

@pranavkm 
Compare to https://github.com/aspnet/KestrelHttpServer/blob/rel/1.0.1/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/project.json

Backdate test dependencies to 1.0 standard versions

---

test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.Tests/project.json

Test projects need imports. This was causing the patch release builds to fail.
FYI @pranavkm @Tratcher Merging now to unblock.

Add imports required for tests

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Properties/AssemblyInfo.cs

As a side effect of merging test projects, there are now sets of similar tests executing in parallel and causing conflicts, especially for things like caching. For now I'm disabling parallel test execution and we can iron out the conflicts later.
#263

Disable parallel test execution to improve reliability

---

src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

#298 
Using the same option name and default as Kestrel.

Add a timeout for draining requests on shutdown

---

global.json
samples/HelloWorld/project.json
samples/HotAddSample/project.json
samples/SelfHostServer/project.json
src/Microsoft.AspNetCore.Server.WebListener/MessagePump.cs
src/Microsoft.AspNetCore.Server.WebListener/project.json
src/Microsoft.Net.Http.Server/project.json
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ServerTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.FunctionalTests/project.json
test/Microsoft.Net.Http.Server.Tests/project.json

#301 Timeout graceful request draining after 5 seconds. No configuration API.
Also bumping the packages versions to 1.1.1.
Replaces https://github.com/aspnet/HttpSysServer/pull/304

1.1.1 Patch - shutdown timeout

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/HttpsTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/HttpsTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/SkipOffDomainAttribute.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/Utilities.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.csproj
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.Tests/Microsoft.AspNetCore.Server.HttpSys.Tests.csproj

- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
- build tests for desktop .NET only on Windows

Bump test projects up to .NET 4.5.2

---

.gitignore
build/dependencies.props
samples/HotAddSample/HotAddSample.csproj
samples/SelfHostServer/SelfHostServer.csproj
samples/SelfHostServer/runtimeconfig.template.json
src/Microsoft.AspNetCore.Server.HttpSys/Microsoft.AspNetCore.Server.HttpSys.csproj
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.csproj
test/Microsoft.AspNetCore.Server.HttpSys.Tests/Microsoft.AspNetCore.Server.HttpSys.Tests.csproj

More version cleanup.
Removed runtimeconfig.template.json. It is no longer required.

Unify dependency versions to one file and remove workarounds

---

src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/UnsafeNativeMethods.cs

#326 
WebListener targets api-ms-win-core-io-l1-1-1.dll for CancelIoEx, but it's actually defined in api-ms-win-core-io-l1-1-0.dll. This is fine on Win8+, but it fails on Win7. This causes an EntryPointNotFoundException when calling the method.

Fix API set target

---

test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.WebListener.FunctionalTests/ResponseCachingTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.Net.Http.Server.FunctionalTests/ResponseCachingTests.cs

#263 These tests are already refactored or disabled in dev.
We'll need a separate PR for 1.1.x.

[Patch 1.0.x] Disable flaky tests

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs

#263 This test was marked as flaky but never disabled. So disable until we can investigate in preview2.

Skip flaky test

---

src/Microsoft.AspNetCore.Server.HttpSys/FeatureContext.cs

https://github.com/aspnet/HttpAbstractions/pull/844
There's an implicit converter from StringValues to string, but it doesn't work transitively with the converter from string to StringSegment. This is probably for the best because the StringValues to string converter may do string concats that we want to be aware of in a perf sensitive context.

React to StringSegment change

---

src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/Response.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseHeaderTests.cs

#339 
HEAD requests don't have response bodies, but they do emulate GET requests that may. HttpSysServer was assuming that the emulated GET request would result in a chunked response so it included the Transfer-Encoding: chunked header. However, it forgot to suppress the chunked terminator. This didn't show up in the tests because they weren't expecting additional data on the connection, and they also weren't re-using connections.
Rather than assuming chunking, it now omits the headers and pretends it's a content-length 0 response.

Don't send chunked responses for HEAD requests

---

src/Microsoft.AspNetCore.Server.HttpSys/FeatureContext.cs
src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/Request.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestContext.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestStream.cs
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/ResponseBody.cs
src/Microsoft.AspNetCore.Server.HttpSys/StandardFeatureCollection.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/HttpsTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/OpaqueUpgradeTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/OpaqueUpgradeTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestBodyLimitTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

#366 Read, Write, and Flush now throw by default. There's some debate on Flush because it breaks StreamWriter.Dispose().

Add flag to disable synchronous IO

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

CI link: http://aspnetci/project.html?tab=testDetails&projectId=XPlat&testNameId=-5004057257646002980&page=1
I could only repro it on a slow VM under load, and increasing the timeout interval seems to fix it.
cc @ryanbrandenburg

Increase timeout in Server_ClientDisconnects_CallCanceled to mitigate test flakiness

---

shared/Microsoft.AspNetCore.HttpSys.Sources/RequestProcessing/NativeRequestContext.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestHeaderTests.cs

#381 The underlying decoders don't allow for length 0 strings. The code comment is pretty obvious, it's not clear why it didn't match the code.

Handle known headers with no value

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs

#270 
These tests were only failing on Win7. Win7 apparently buffers less data so SendFileAsync was not completing. The fix is to have the client start consuming the data. The client won't finish/succeed because this is an abort test, but at least the server gets unblocked now.

Fix hang in SendFile tests

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/Utilities.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Reenable skipped tests from #263. I was only able to reproduce the flakyness by running the test suite in parallel with other universe builds. Not sure what the actual conflict but this situation should never occur on our current CI infrastructure. It should be safe to turn these tests back on. In any case, we should turn these tests back on so we can collect details on what fails as the old build links are no longer available.

Reenable skipped tests

---

src/Microsoft.AspNetCore.Server.HttpSys/AsyncAcceptContext.cs

This is a regression in post-2.0 refactoring. It fails to dispose an object pinned via a native overlapped object so it stays rooted indefinitely.

Dispose of the existing native context before creating a new one.

---

src/Microsoft.AspNetCore.Server.HttpSys/AsyncAcceptContext.cs

This was missed in the prior PR that added the Dispose call. It was triggering a Debug.Assert which for CoreFx caused the test run to terminate early without reporting a failure. When run from the command line the Net461 tests properly reported a failure for the assert.
This primarily triggers on WindowsAuth tests which only run on domain joined machines.
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
RequestContextBase::Dispose()|Dispose() called before ReleasePins().
at Microsoft.AspNetCore.HttpSys.Internal.NativeRequestContext.Dispose()
at Microsoft.AspNetCore.Server.HttpSys.AsyncAcceptContext.AllocateNativeRequest(Nullable`1 size, UInt64 requestId)
at Microsoft.AspNetCore.Server.HttpSys.AsyncAcceptContext.IOComplet …
```

Release pins before disposal

---

shared/Microsoft.AspNetCore.HttpSys.Sources/RequestProcessing/RawUrlHelper.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestTests.cs

Fix for #405. At this point there are no tests for the Internal namespace, hence I didn't add any for now. We should consider adding them in the future?

Fix parsing error on urls without path.

---

src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/NativeRequestContext.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestHeaderTests.cs

#410 Backport of https://github.com/aspnet/HttpSysServer/pull/401
@muratg I'm not planning to add a quirk flag for this behavior. The error is very disruptive and the fix is very low risk.

Fix issue reading empty known headers

---

build/dependencies.props
src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestStream.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestBodyLimitTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/RequestBodyTests.cs

https://github.com/aspnet/Coherence-Signed/issues/792
Pre-emptivly making changes for when the new SocketsHttpHandler becomes the default in preview2. This addresses all but the known NTLM issue they have already fixed in a later build.
There are two types of changes here:
1. SocketsHttpHandler does not flush it's headers before it starts sending the body so body data may arrive in the same packet and get included to Http.Sys's Request data structure. Reads must check the request structure before reading from the network. This code path has had very little testing and made some assumptions that need updating. Before, if the pre-buffered data didn't fill the users read buffer it would issue a second read to the network. This change drops that second read in favor of completing immediately, …

React to new SocketHttpHandler

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs

#439 This test was broken by the recent switch to SocketsHttpHandler and it looks like a bug in the client. Disabling the test until we can get a fix.

Disable regressed negotiate test

---

build/dependencies.props
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/AuthenticationTests.cs

We took an updated SocketsHttpHandler that fixed the regression in #439.
Also, now that SocketsHttpHandler is the default in 2.1 https://github.com/aspnet/ServerTests/issues/82 is no longer a problem. Using #ifdef so these are now enabled on NETCOREAPP2.1 and NET461 and disabled on NETCOREAPP2.0.

Renable auth tests with new HttpClient

---

src/Microsoft.AspNetCore.Server.HttpSys/Http503ResponseVerbosityLevel.cs
src/Microsoft.AspNetCore.Server.HttpSys/Http503VerbosityLevel .cs
src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs
src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/RequestQueue.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs

Changes discussed offline with Chris earlier this morning to expose Http503ResponseVebosityLevel. Feature request tracked in the backlog already under: https://github.com/aspnet/HttpSysServer/issues/364
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364509(v=vs.85).aspx
I am submitting this to get unblocked for the migration of our UniversalStore services from Owin/Katana + WebApi 2.0 to Asp.Net Core

#364 - Expose HTTP_503_RESPONSE_VERBOSITY option

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/AuthenticationTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/HttpsTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/OpaqueUpgradeTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/RequestTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseBodyTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseHeaderTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseSendFileTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/Utilities.cs

#457 This series of tests runs the client and server inline asynchronously. Some of them have been flaky and we added timeouts to prevent them from hanging. However that timeout doesn't explain why it failed. One theory is that the client encountered an error before the request reached the server, but we time out before we await that task so the error goes unreported.
I've added an extension that surfaces the error details if the request fails before the server receives it. 
/cc: @ryanbrandenburg

Add diagnostics to debug flaky tests

---

shared/Microsoft.AspNetCore.HttpSys.Sources/Constants.cs
shared/Microsoft.AspNetCore.HttpSys.Sources/NativeInterop/HttpApiTypes.cs
shared/Microsoft.AspNetCore.HttpSys.Sources/RequestProcessing/NativeRequestContext.cs
src/Microsoft.AspNetCore.Server.HttpSys/FeatureContext.cs

This is the small part of #106 where we surface "HTTP/2" in Request.Protocol. ANCM in-proc will need a similar change.
Push promise is not happening until some future milestone.

Show HTTP/2 status on requests

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs

#474 CoreFx has fixed the regression.

Re-enable skipped auth test

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Listener/ResponseCachingTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ResponseCachingTests.cs

https://github.com/aspnet/HttpSysServer/issues/451#issuecomment-423648929
I can't reproduce that test failure locally. I'm only adding this change as a theory that it can help prevent false positives and negatives when content is cached across requests.

Use GUIDs for cache tests

---

test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/ServerTests.cs
test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Utilities.cs

#472 #476 #469 These tests have had a few sporadic failures that we can't reproduce. This is some test cleanup that could help avoid races by not creating two server instances per test.

Cleanup server limits tests
